begin;
do $test$
declare a uuid; e uuid; other uuid; atok text; etok text; otok text; r jsonb; lid uuid; wid uuid; v int; doc uuid;
begin
insert into akbs_crm.users(login,name,role,password_hash,must_change_password) values ('qa-'||gen_random_uuid()||'@example.invalid','QA Administrator','ADMIN',extensions.crypt('Temporary-test-password-2026',extensions.gen_salt('bf',4)),false) returning id into a;
insert into akbs_crm.users(login,name,role,password_hash,must_change_password) values ('qa-'||gen_random_uuid()||'@example.invalid','QA Employee','EMPLOYEE',extensions.crypt('Temporary-test-password-2026',extensions.gen_salt('bf',4)),false) returning id into e;
insert into akbs_crm.users(login,name,role,password_hash,must_change_password) values ('qa-'||gen_random_uuid()||'@example.invalid','QA Other','EMPLOYEE',extensions.crypt('Temporary-test-password-2026',extensions.gen_salt('bf',4)),false) returning id into other;
r:=public.akbs_crm_workspace('login',jsonb_build_object('login',(select login from akbs_crm.users where id=a)));
assert r->>'status'='401','Missing password must be denied';
r:=public.akbs_crm_workspace('login',jsonb_build_object('login',(select login from akbs_crm.users where id=a),'password','Temporary-test-password-2026'));
assert r ? 'token','Password login failed'; atok:=r->>'token';
etok:=akbs_crm.workspace_session(e); otok:=akbs_crm.workspace_session(other);
r:=public.akbs_crm_workspace('snapshot','{}','invalid');assert r->>'status'='401','Anonymous read allowed';
r:=public.akbs_crm_workspace('lead_create',jsonb_build_object('name','QA Rollback Lead','phone','9999999999','capacity',1000,'project_cost',50000,'details',jsonb_build_object('state','QA State')),atok);
assert not(r ? 'error'),'Lead create failed';lid:=(r#>>'{lead,id}')::uuid;
assert (select assigned_to is not null from akbs_crm.leads where id=lid),'Auto assignment failed';
assert (select details->>'state'='QA State' from akbs_crm.leads where id=lid),'Details not saved';
select version into v from akbs_crm.leads where id=lid;
r:=public.akbs_crm_workspace('lead_update',jsonb_build_object('lead_id',lid,'version',v,'assigned_to',e),atok);assert not(r ? 'error'),'Admin assignment failed';
select version into v from akbs_crm.leads where id=lid;
r:=public.akbs_crm_workspace('lead_update',jsonb_build_object('lead_id',lid,'version',v,'assigned_to',other),etok);assert r->>'status'='403','Employee reassignment allowed';
r:=public.akbs_crm_workspace('note',jsonb_build_object('lead_id',lid,'note','Not my lead'),otok);assert r->>'status'='404','Other employee can write lead';
r:=public.akbs_crm_workspace('lead_update',jsonb_build_object('lead_id',lid,'version',v-1,'name','Stale'),atok);assert r->>'status'='409','Stale write allowed';
r:=public.akbs_crm_workspace('note',jsonb_build_object('lead_id',lid,'note','Follow up tomorrow','kind','CALL'),etok);assert not(r ? 'error'),'Call logging failed';
r:=public.akbs_crm_workspace('workflow_create',jsonb_build_object('lead_id',lid,'kind','followup','title','QA follow-up','status','SCHEDULED','due_at',now()+interval '1 day'),etok);assert not(r ? 'error'),'Followup failed';wid:=(r->>'id')::uuid;
r:=public.akbs_crm_workspace('workflow_update',jsonb_build_object('id',wid,'version',1,'lead_id',lid,'kind','followup','title','QA follow-up','status','COMPLETED','due_at',now()+interval '1 day'),etok);assert not(r ? 'error'),'Workflow completion failed';
r:=public.akbs_crm_workspace('document_upload',jsonb_build_object('lead_id',lid,'name','QA.txt.pdf','category','Test','mime','application/pdf','size',5,'content','JVBERi0='),etok);assert not(r ? 'error'),'Document upload failed';doc:=(r->>'id')::uuid;
r:=public.akbs_crm_workspace('document_download',jsonb_build_object('id',doc),otok);assert r->>'status'='404','Unauthorized document allowed';
r:=public.akbs_crm_workspace('document_download',jsonb_build_object('id',doc),etok);assert r->>'content'='JVBERi0=','Document roundtrip failed';
r:=public.akbs_crm_workspace('template_save',jsonb_build_object('title','QA','channel','email','body','QA'),etok);assert r->>'status'='403','Employee template change allowed';
r:=public.akbs_crm_workspace('snapshot','{}',etok);assert exists(select 1 from jsonb_array_elements(r->'leads') x where x->>'id'=lid::text),'Employee lead absent';
assert not exists(select 1 from jsonb_array_elements(r->'users') x where x ? 'password_hash'),'Password leaked';
r:=public.akbs_crm_workspace('workflow_create',jsonb_build_object('lead_id',lid,'kind','proposal','title','QA proposal','status','DRAFT','amount',50000),atok);assert not(r ? 'error'),'Proposal draft failed';wid:=(r->>'id')::uuid;
r:=public.akbs_crm_workspace('workflow_update',jsonb_build_object('id',wid,'version',1,'lead_id',lid,'kind','proposal','title','QA proposal','status','UNDER_REVIEW'),atok);assert not(r ? 'error'),'Proposal review failed';
r:=public.akbs_crm_workspace('workflow_update',jsonb_build_object('id',wid,'version',2,'lead_id',lid,'kind','proposal','title','QA proposal','status','APPROVED'),atok);assert not(r ? 'error'),'Proposal approval failed';
r:=public.akbs_crm_workspace('workflow_update',jsonb_build_object('id',wid,'version',3,'lead_id',lid,'kind','proposal','title','QA proposal','status','SENT'),atok);assert not(r ? 'error'),'Proposal sent status failed';
r:=public.akbs_crm_workspace('workflow_update',jsonb_build_object('id',wid,'version',4,'lead_id',lid,'kind','proposal','title','QA proposal','status','ACCEPTED'),atok);assert not(r ? 'error'),'Proposal acceptance failed';
select version into v from akbs_crm.leads where id=lid;
r:=public.akbs_crm_workspace('lead_update',jsonb_build_object('lead_id',lid,'version',v,'approval','APPROVED'),atok);assert not(r ? 'error'),'Lead approval failed';
r:=public.akbs_crm_workspace('lead_update',jsonb_build_object('lead_id',lid,'version',v+1,'stage','CONVERTED'),atok);assert not(r ? 'error'),'Customer conversion failed';
assert (select stage='CONVERTED' from akbs_crm.leads where id=lid),'Conversion not persisted';
r:=public.akbs_crm_workspace('logout','{}',etok);
r:=public.akbs_crm_workspace('snapshot','{}',etok);assert r->>'status'='401','Logout failed';
end $test$;
rollback;
