import React,{useCallback,useEffect,useState} from 'react';
import {ArrowLeft,RefreshCw,Search,FilePenLine} from 'lucide-react';
import {secureRequest} from '../lib/secureRequest';
import {draftProgress,groupsFor,type PortalKind} from '../lib/incompleteApplications';
import type {Lead} from '../types';
type Row={requestId:string;email:string;name:string;mobile:string;form:Record<string,any>;signupAt:string;updatedAt:string};
const date=(v:string)=>v?new Date(v).toLocaleString('en-IN'):'—';
export function IncompleteApplications({kind,onBack,onCompleted,inquiries=[],onOpenInquiry}:{kind:PortalKind;onBack:()=>void;onCompleted:()=>void;inquiries?:Lead[];onOpenInquiry?:(lead:Lead)=>void}){
 const [rows,setRows]=useState<Row[]>([]),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState('');
 const [selected,setSelected]=useState<Row|null>(null),[form,setForm]=useState<Record<string,any>>({}),[consent,setConsent]=useState(false);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const call=useCallback((action:string,data:Record<string,unknown>={})=>secureRequest('akbs_incomplete_applications',{p_action:action,p_kind:kind,p_data:data}),[kind]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const out=await call('list',{offset,search});setRows(out.rows||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}},[call,offset,search]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{const t=setTimeout(()=>{setSearch(query);setOffset(0);},300);return()=>clearTimeout(t);},[query]);
 async function open(row:Row){setBusy(true);setError('');setNotice('');try{const out=await call('get',{email:row.email,requestId:row.requestId});if(out.completed){setNotice(`Already submitted: ${out.reference}`);await refresh();return;}setSelected({...row,...out});setForm(out.form);setConsent(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function save(complete=false){if(!selected)return;setBusy(true);setError('');setNotice('');try{const out=await call(complete?'complete':'save',{email:selected.email,requestId:selected.requestId,expectedUpdatedAt:selected.updatedAt,form:{...form,...(kind==='customer'?{supportNeeded:typeof form.supportNeeded==='string'?form.supportNeeded.split(',').map((v:string)=>v.trim()).filter(Boolean):form.supportNeeded}: {})},consentConfirmed:consent});if(out.completed){setSelected(null);setNotice(`${kind==='customer'?'Lead created':'Partner submitted for approval'}: ${out.reference}`);onCompleted();await refresh();}else{setSelected({...selected,form,updatedAt:out.updatedAt});setNotice('Draft saved.');await refresh();}}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const title=kind==='customer'?'Incomplete Applications':'Incomplete Registrations';
 async function reminder(row:Row|Lead,isInquiry=false){
  setBusy(true);setError('');setNotice('');
  try{
   const target=isInquiry?{leadId:(row as Lead).id}:{draftKind:kind,draftEmail:row.email,draftRequestId:(row as Row).requestId};
   const out=await secureRequest('akbs-fee-reminder-email',{...target,purpose:'registration',requestId:crypto.randomUUID()});
   setNotice(`Registration completion reminder emailed to ${out.email}.`);
  }catch(e:any){setError(e.message||'Unable to send completion reminder.');}
  finally{setBusy(false);}
 }
 return <section className="fixed inset-0 z-[90] overflow-y-auto bg-slate-50 text-slate-800 p-4 sm:p-6 lg:p-8 space-y-5">
  <button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-emerald-800"><ArrowLeft size={16}/>Back to {kind==='customer'?'Leads':'Partners'}</button>
  <div className="flex flex-wrap gap-3 justify-between items-center"><div><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="text-sm text-slate-500 mt-1">{kind==='customer'?'Verified customers who have not submitted their application.':'Saved partner registrations awaiting completion. Approval and activation remain separate.'}</p></div><button onClick={()=>void refresh()} disabled={loading} className="rounded-xl border bg-white p-3" aria-label="Refresh incomplete applications"><RefreshCw size={18}/></button></div>
  {error&&<p role="alert" className="rounded-xl bg-rose-50 border border-rose-200 p-3 text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 border border-emerald-200 p-3 text-emerald-800">{notice}</p>}
  <label className="flex gap-2 items-center rounded-xl border bg-white p-3"><Search size={18}/><input className="w-full outline-none" aria-label="Search incomplete applications" placeholder="Search name, mobile or email" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-sm text-left"><thead className="bg-slate-50 text-slate-500"><tr>{['Name / Contact','Last completed step','Completion','Signup / OTP','Last activity','Action'].map(h=><th key={h} className="p-4 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map(row=>{const p=draftProgress(kind,row.form);return <tr key={row.requestId} className="border-t"><td className="p-4"><p className="font-semibold">{row.name||'Name not entered'}</p><p className="text-xs text-slate-500">{row.mobile||'Mobile not entered'}</p><p className="text-xs text-slate-500">{row.email}</p></td><td className="p-4">{p.lastCompleted}</td><td className="p-4 min-w-28"><b>{p.percent}%</b><div className="mt-2 h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-emerald-600" style={{width:`${p.percent}%`}}/></div></td><td className="p-4 text-xs">{date(row.signupAt)}</td><td className="p-4 text-xs">{date(row.updatedAt)}</td><td className="p-4"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void open(row)} className="inline-flex whitespace-nowrap gap-2 items-center rounded-xl bg-emerald-900 text-white px-3 py-2 font-semibold"><FilePenLine size={16}/>Open & Complete</button>{kind==='customer'&&<button disabled={busy||!row.email} onClick={()=>void reminder(row)} className="rounded-xl border border-emerald-200 px-3 py-2 text-emerald-800 font-semibold disabled:opacity-50">Email Completion Reminder</button>}</div></td></tr>;})}</tbody></table>{loading&&<p className="p-5 text-slate-500">Loading saved applications…</p>}{!loading&&!rows.length&&<p className="p-6 text-slate-500">No incomplete {kind==='customer'?'applications':'registrations'} found.</p>}</div>
  <div className="flex justify-end gap-3"><button disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-50))} className="disabled:opacity-40">Previous</button><span>Page {offset/50+1}</span><button disabled={rows.length<50||loading} onClick={()=>setOffset(offset+50)} className="disabled:opacity-40">Next</button></div>
  {kind==='customer'&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Website Inquiries · Registration Not Started</h2><p className="text-sm text-slate-500 mt-1">Website contact forms are leads. Registration and fee collection begin after the customer submits the application.</p><div className="mt-4 divide-y">{inquiries.filter(l=>!query||[l.name,l.phone,l.email].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))).map(lead=><div key={lead.id} className="py-4 flex flex-wrap items-center justify-between gap-3"><div><b>{lead.name}</b><p className="text-xs text-slate-500">{lead.phone} · {lead.email}</p><p className="text-xs text-slate-500">Source: Website Inquiry Form · Registration required</p></div><div className="flex gap-2"><button disabled={busy||!lead.email} onClick={()=>void reminder(lead,true)} className="rounded-xl bg-emerald-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Email Registration Reminder</button>{onOpenInquiry&&<button onClick={()=>onOpenInquiry(lead)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Open Lead</button>}</div></div>)}{!inquiries.length&&<p className="py-4 text-sm text-slate-500">No website inquiries awaiting registration.</p>}</div></section>}
  {selected&&<div className="fixed inset-0 z-[100] bg-slate-950/50 flex justify-end" role="dialog" aria-modal="true" aria-label="Complete saved application"><form className="w-full max-w-3xl bg-white text-slate-800 h-full overflow-y-auto p-5 sm:p-8" onSubmit={e=>{e.preventDefault();void save(true);}}><div className="flex justify-between items-start gap-3"><div><h2 className="text-xl font-bold">Open & Complete</h2><p className="text-sm text-slate-500">{selected.email} · Admin-assisted completion</p></div><button type="button" disabled={busy} onClick={()=>setSelected(null)} className="font-bold text-slate-500">Close</button></div>
   {error&&<p role="alert" className="my-4 text-rose-700">{error}</p>}{notice&&<p role="status" className="my-4 text-emerald-700">{notice}</p>}
   <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><b>Saved progress: {draftProgress(kind,form).percent}%</b><p>Last completed section: {draftProgress(kind,form).lastCompleted}</p><p>Last saved: {date(selected.updatedAt)}</p><p className="mt-2">The applicant’s saved details are filled below. Continue the remaining fields, save progress, or complete the application.</p></div>
   {groupsFor(kind).map(g=><fieldset key={g.title} className="mt-6"><legend className="font-bold text-emerald-900 mb-3">{g.title}</legend><div className="grid sm:grid-cols-2 gap-4">{g.fields.map(f=>{const value=Array.isArray(form[f.key])?form[f.key].join(', '):String(form[f.key]??'');const common={className:'mt-1 w-full rounded-lg border border-slate-300 p-2.5 bg-white',value,required:f.required||f.key==='approxLoanAmount'&&form.needsLoan==='Yes',disabled:busy||f.key==='email',onChange:(e:any)=>setForm({...form,[f.key]:e.target.value})};return <label className="text-sm text-slate-600" key={f.key}>{f.label}{common.required?' *':''}{f.options?<select {...common}><option value="">Select…</option>{!f.options.includes(value)&&value&&<option>{value}</option>}{f.options.map(v=><option key={v}>{v}</option>)}</select>:f.type==='textarea'?<textarea {...common} rows={3}/>:<input {...common} maxLength={f.type==='array'?3000:5000}/>}</label>;})}</div></fieldset>)}
   <label className="flex gap-3 mt-6 p-4 rounded-xl bg-amber-50 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>I have confirmed the details and declaration/contact consent with the applicant, and am authorized to submit on their behalf. My admin identity will be recorded.</span></label>
   <div className="flex flex-wrap gap-3 mt-6 pb-8"><button type="button" disabled={busy} onClick={()=>void save(false)} className="rounded-xl border px-5 py-3 font-bold">Save draft</button><button disabled={busy||!consent} className="rounded-xl bg-emerald-900 text-white px-5 py-3 font-bold disabled:opacity-40">{busy?'Saving…':kind==='customer'?'Complete & Create Lead':'Complete & Send for Approval'}</button></div>
  </form></div>}
 </section>;
}
